### ISSUE TITLE
Consistency of food web collection types

### ISSUE THREAD

**Issue by gvdr** [PoisotLab/EcologicalNetworks.jl#177]
_This is more a personal idea than a real issue, please consider it kindly._

I opened the issue because I notice an inconsistency in the way the three function that give access to the packaged food webs are returned (maybe it's wanted).

In particular:
1. `web_of_life()` returns an Array of NamedTuples
```julia
Array{NamedTuple{(:ID, :Species, :Interactions, :Connectance, :Type_of_interactions, :Type_of_data, :Reference, :Locality_of_Study, :Latitude, :Longitude),T} where T<:Tuple,1}
```
2. `pajek()` returns a Dictionary
```julia
Dict{Symbol,UnipartiteQuantitativeNetwork}
```
3. `nz_stream_foodweb()` returns and Array of UnipartiteNetworks
```julia
Array{UnipartiteNetwork{Bool,String},1}
```

For a user like me it may make more sense to return the webs in the same format (maybe with an optional argument: `nets = true` to return everything as an Array of either Bipartite or Unipartite Networks?).

On the other hand, this behaviour may be useful to showcase different things, and it is quite straightforward to convert everything in the right format afterward.

**Comment by tpoisot** [comment]
I agree - this has bugged me (and students during a class) in a few occasions. One of the reasons is that `web_of_life` has metadata, and the others don't. One of the ways I thought about fixing this problem was to (i) have a script pull mangal (all of it) into a repo and (ii) on build, draw the networks from this dump.
This would be a complete overhaul of the data component, which is needed anyways.
